### ISSUE TITLE
Restarter must be created only during owner's initialization stage

### ISSUE THREAD

**Issue by nathlrowe** [olshevski/compose-navigation-reimagined#6]
I'm getting the following error and I'm not sure what is causing it:

```
java.lang.IllegalStateException: Restarter must be created only during owner's initialization stage
        at androidx.savedstate.SavedStateRegistryController.performRestore(SavedStateRegistryController.java:58)
        at dev.olshevski.navigation.reimagined.NavComponentEntry.restoreState$reimagined_release(NavComponentEntry.kt:83)
        at dev.olshevski.navigation.reimagined.NavComponentHolder.newComponentEntry(NavComponentHolder.kt:148)
        at dev.olshevski.navigation.reimagined.NavComponentHolder.access$newComponentEntry(NavComponentHolder.kt:75)
        at dev.olshevski.navigation.reimagined.NavComponentHolder$lastComponentEntry$1.invoke(NavComponentHolder.kt:101)
        at dev.olshevski.navigation.reimagined.NavComponentHolder$lastComponentEntry$1.invoke(NavComponentHolder.kt:97)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1798)
        at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:117)
        at androidx.compose.runtime.DerivedSnapshotState.getCurrentValue(DerivedState.kt:167)
        at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:161)
        at dev.olshevski.navigation.reimagined.NavComponentHolder.setPostTransitionLifecycleStates(NavComponentHolder.kt:171)
        at dev.olshevski.navigation.reimagined.NavComponentHolder.onTransitionFinish(NavComponentHolder.kt:162)
        at dev.olshevski.navigation.reimagined.BaseNavHostKt$BaseNavHost$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:484)
        at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:85)
        at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:793)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:647)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:488)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:984)
        at android.view.Choreographer.doCallbacks(Choreographer.java:764)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

This started happening when I updated from beta02 to beta03. I don't think I changed anything with my code that would have resulted in something like this.

**Comment by nathlrowe** [comment]
Update: downgraded to beta02 and am still experiencing this, so not a problem with the latest update specifically at least.

**Comment by olshevski** [comment]
I wonder what you are doing to cause the state I'm seeing in the stacktrace. More information would be really helpful in order to reproduce the issue. Does it happen in some particular case? Is there a nested navigation in your app? Are you using NavHost or AnimatedNavHost? Maybe some steps if you can find one. 

Or maybe you can show me the code (not private one, but some barebones demo app would suffice).

**Comment by nathlrowe** [comment]
I haven't been able to reproduce it. Pretty much just un-did a bunch of stuff and haven't been able to re-produce it.
